Fix NoClassDefFoundError exception while parser generation with 2020.1 platform
This change adds `platform-concurrency.jar` into `Grammar-Kit` classpath because `MergeQuery` class (used by `Grammar-Kit`) was moved from `platform-api` module to `platform-concurrency` one.